Revert "[open][neva_upstreamable][ozone] Deactivate text_model when the text entry lost focus"
:Release Notes:
This reverts commit fc1b7bcdcf3ff539cb0f97aa7f3aec1892fba6a7.

:Detailed Notes:
Causes build failure:
| In file included from ../../git/src/ozone/wayland/window.cc:22:
| ../../git/src/ozone/wayland/display.h:46:10: fatal error:
| ui/base/ime/neva/input_method_common.h: No such file or directory
|  #include "ui/base/ime/neva/input_method_common.h"
|           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| compilation terminated.

:Testing Performed:
check build

:QA Notes:
Test-cases: N/A

:Issues Addressed:

Change-Id: If78338dbeb800b3c3ec0a8c6cc404a1039f6ad43
Reviewed-on: http://gpro.lge.com/243744