fixup! [open][neva_upstreamable][keep_alive] Implement keep alive feature
:Release Notes:
Fix compilation issue due to missing headers

:Detailed Notes:
Fix compilation issue:
| src/content/browser/renderer_host/delegated_frame_host_neva.cc:43:26:
| error: 'CreateSingleThreadTaskRunnerWithTraits' is not a member of 'base'
|     task_runner_ = base::CreateSingleThreadTaskRunnerWithTraits(

and

| src/content/browser/renderer_host/delegated_frame_host_neva.cc:45:37:
| error: invalid initialization of reference of type 'const base::TaskTraits&'
| from expression of type '<brace-enclosed initializer list>'
|         {content::BrowserThread::UI});

:Testing Performed:
Check build

:QA Notes:
Test-cases: N/A

:Issues Addressed:
[PLAT-80707] Compile error with keepalive patches

Change-Id: I8f6ec64a38eb5947bbc53eb4cd7642a5340cf772
Reviewed-on: http://gpro.lge.com/245040